#pragma once

#include <lepton.h>

#define _BOOTLOADER_EXCEPTION_METHODS(TYPE, SUPER, FUNC)

#define BOOTLOADER_EXCEPTION_METHODS(TYPE, SUPER, FUNC) \
    THROWABLE_METHODS(TYPE, SUPER, FUNC) \
    _BOOTLOADER_EXCEPTION_METHODS(TYPE, SUPER, FUNC)

CLASSDEF(BootloaderException, Exception, BOOTLOADER_EXCEPTION_METHODS)

ENDCLASSDEF(BootloaderException)
