#include <exception/console_exception.h>

INHERITCLASS(ConsoleException, _CONSOLE_EXCEPTION_METHODS, BOOTLOADER_EXCEPTION_METHODS)

PACKAGECLASS(ConsoleException, BootloaderException, _CONSOLE_EXCEPTION_METHODS, BOOTLOADER_EXCEPTION_METHODS)
