#include <exception/file_exception.h>

INHERITCLASS(FileException, _FILE_EXCEPTION_METHODS, BOOTLOADER_EXCEPTION_METHODS)

PACKAGECLASS(FileException, BootloaderException, _FILE_EXCEPTION_METHODS, BOOTLOADER_EXCEPTION_METHODS)
