#pragma once

#include <lepton/exception/exception.h>

#define _INVALIDPARAMETER_EXCEPTION_METHODS(TYPE, SUPER, FUNC)

#define INVALIDPARAMETER_EXCEPTION_METHODS(TYPE, SUPER, FUNC) \
    THROWABLE_METHODS(TYPE, SUPER, FUNC) \
    _INVALIDPARAMETER_EXCEPTION_METHODS(TYPE, SUPER, FUNC)

CLASSDEF(InvalidParameterException, Exception, INVALIDPARAMETER_EXCEPTION_METHODS)
ENDCLASSDEF(InvalidParameterException)
