#pragma once

#include <lepton/exception/exception.h>

#define _NOSUCHENUMMEMBER_EXCEPTION_METHODS(TYPE, SUPER, FUNC)

#define NOSUCHENUMMEMBER_EXCEPTION_METHODS(TYPE, SUPER, FUNC) \
    THROWABLE_METHODS(TYPE, SUPER, FUNC) \
    _NOSUCHENUMMEMBER_EXCEPTION_METHODS(TYPE, SUPER, FUNC)

CLASSDEF(NoSuchEnumMemberException, Exception, NOSUCHENUMMEMBER_EXCEPTION_METHODS)
ENDCLASSDEF(NoSuchEnumMemberException)
